name: Build and deploy agil it bcrm backend applicatoion

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: buld and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: action/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build the aplication
        run: |
          mvn clean
          mvn -B package --file pom.xml
